"""Certified rules as Open Policy Agent policy.

The pitch this changes: not "we produce a report you read" but "we compile
regulation into the policy engine your infrastructure already runs". A firm with
OPA in its stack can evaluate SEBI obligations in the same place it evaluates
everything else.

**Only a subset maps, and the export says which.** A rule whose deadline runs
from a named event, or whose day count nobody has resolved, cannot become a
decision an engine can take without somebody inventing the missing piece. Those
are refused and listed by clause, so what comes out is a policy that is complete
about a stated subset rather than a policy that looks complete and is not.

The generated Rego is deliberately plain: one rule per obligation, a data
document of deadlines, and a single `deny` set. It is meant to be read by the
compliance engineer who has to trust it, not to be clever.
"""

from __future__ import annotations

import datetime as _dt
import re
from dataclasses import dataclass, field

from sanhita.ir.enums import DayCount, DeadlineKind, Modality, RuleStatus
from sanhita.ir.schema import Obligation

__all__ = ["RegoExport", "Untranslatable", "to_rego"]

_SAFE = re.compile(r"[^a-z0-9_]+")


def _ident(text: str) -> str:
    """A Rego-safe identifier that still reads like the clause it came from."""
    out = _SAFE.sub("_", text.lower()).strip("_")
    return f"r_{out}" if not out or out[0].isdigit() else out


@dataclass(frozen=True)
class Untranslatable:
    obligation_id: str
    clause_id: str
    reason: str

    def to_json(self) -> dict:
        return {
            "obligation_id": self.obligation_id,
            "clause_id": self.clause_id,
            "reason": self.reason,
        }


@dataclass
class RegoExport:
    policy: str = ""
    translated: int = 0
    refused: list[Untranslatable] = field(default_factory=list)
    certified: int = 0

    @property
    def coverage(self) -> float:
        return self.translated / self.certified if self.certified else 0.0

    def summary(self) -> str:
        return (
            f"{self.translated} of {self.certified} certified rules became "
            f"policy. {len(self.refused)} could not, and are listed in the "
            "header of the file rather than dropped."
        )

    def to_json(self) -> dict:
        return {
            "translated": self.translated,
            "certified": self.certified,
            "coverage": self.coverage,
            "refused": [r.to_json() for r in self.refused],
        }


def _why_not(o: Obligation) -> str | None:
    """The reason this rule cannot become an executable policy, or None."""
    if o.modality not in (Modality.MUST, Modality.SHOULD):
        return (
            f"modality is {o.modality.value}; a policy engine can only enforce a "
            "duty, not a permission"
        )
    if o.deadline is None:
        return "the clause sets no deadline, so there is nothing to evaluate against"
    if o.deadline.kind is DeadlineKind.ON_DEMAND:
        return "the clock starts on a demand, which is not something a policy can see"
    if o.deadline.offset_days is None and o.deadline.kind is DeadlineKind.RELATIVE:
        return "the deadline is not expressed in days"
    if (
        o.deadline.offset_days
        and o.deadline.business_days is DayCount.UNSPECIFIED
    ):
        return (
            "nobody has resolved whether the days are working or calendar, and "
            "the export will not choose"
        )
    if not o.evidence:
        return "the clause names no artifact, so there is nothing to check for"
    return None


def to_rego(
    obligations: list[Obligation],
    *,
    package: str = "sanhita.obligations",
    circular: str = "SEBI Master Circular for Stock Brokers",
) -> RegoExport:
    """Translate the certified rules that can be translated."""
    certified = [o for o in obligations if o.status is RuleStatus.CERTIFIED]
    export = RegoExport(certified=len(certified))

    usable: list[Obligation] = []
    for o in sorted(certified, key=lambda o: o.id):
        problem = _why_not(o)
        if problem:
            export.refused.append(
                Untranslatable(o.id, o.source.clause_id, problem)
            )
        else:
            usable.append(o)
    export.translated = len(usable)

    lines: list[str] = []
    add = lines.append

    add(f"# Generated by Sanhita from {circular}.")
    add(f"# {_dt.datetime.now(_dt.timezone.utc).isoformat()}")
    add("#")
    add("# Every rule below was signed by a named person. The signature and the")
    add("# clause it came from travel with it, so a decision this policy takes")
    add("# can be traced back to the sentence in the regulation that requires it.")
    add("#")
    add(f"# {export.translated} of {export.certified} certified rules are here.")
    if export.refused:
        add(f"# The other {len(export.refused)} could not be expressed as policy:")
        for r in export.refused[:40]:
            add(f"#   {r.clause_id:<14} {r.reason}")
        if len(export.refused) > 40:
            add(f"#   ... and {len(export.refused) - 40} more")
        add("#")
        add("# They are NOT enforced by this policy. Anything relying on it must")
        add("# treat that list as a gap rather than as compliance.")
    add("")
    add(f"package {package}")
    add("")
    add("import future.keywords.if")
    add("import future.keywords.in")
    add("")
    add("# input schema")
    add("#   input.events[_] = {")
    add('#     "obligation_id": "SB-19.4.3-a",')
    add('#     "entity":        "Some Broking Pvt Ltd",')
    add('#     "occurred_on":   "2026-03-16",   # days since epoch also accepted')
    add('#     "filed_on":      "2026-03-20"    # null when never filed')
    add("#   }")
    add("")

    add("# The deadline each obligation allows, and the clause that says so.")
    add("obligations := {")
    for o in usable:
        d = o.deadline
        days = d.offset_days or 0
        add(f'\t"{o.id}": {{')
        add(f'\t\t"clause":      "{o.source.clause_id}",')
        add(f'\t\t"page":        {o.source.page},')
        add(f'\t\t"actor":       "{o.actor.value}",')
        add(f'\t\t"requirement": "{_escape(o.action.verb + " " + o.action.object)}",')
        add(f'\t\t"days":        {days},')
        add(f'\t\t"day_count":   "{d.business_days.value}",')
        add(f'\t\t"artifact":    "{_escape(o.evidence[0].artifact_type)}",')
        add(f'\t\t"certified_by":"{_escape(o.certification.certified_by)}",')
        add(f'\t\t"signature":   "{o.certification.signature}",')
        add("\t},")
    add("}")
    add("")

    add("# A duty is breached when the artifact was never filed, or filed after")
    add("# the deadline the clause allows. Working days are not modelled here:")
    add("# a CALENDAR rule is exact, a BUSINESS rule is evaluated on calendar")
    add("# days and so is conservative, never lenient.")
    add("deny contains finding if {")
    add("\tsome event in input.events")
    add("\trule := obligations[event.obligation_id]")
    add("\tevent.filed_on == null")
    add("\tfinding := {")
    add('\t\t"outcome":      "MISSING",')
    add('\t\t"entity":       event.entity,')
    add('\t\t"obligation":   event.obligation_id,')
    add('\t\t"clause":       rule.clause,')
    add('\t\t"page":         rule.page,')
    add('\t\t"requirement":  rule.requirement,')
    add('\t\t"certified_by": rule.certified_by,')
    add('\t\t"signature":    rule.signature,')
    add("\t}")
    add("}")
    add("")
    add("deny contains finding if {")
    add("\tsome event in input.events")
    add("\trule := obligations[event.obligation_id]")
    add("\tevent.filed_on != null")
    add("\tlate := days_between(event.occurred_on, event.filed_on) - rule.days")
    add("\tlate > 0")
    add("\tfinding := {")
    add('\t\t"outcome":      "LATE",')
    add('\t\t"entity":       event.entity,')
    add('\t\t"obligation":   event.obligation_id,')
    add('\t\t"clause":       rule.clause,')
    add('\t\t"page":         rule.page,')
    add('\t\t"requirement":  rule.requirement,')
    add('\t\t"days_late":    late,')
    add('\t\t"certified_by": rule.certified_by,')
    add('\t\t"signature":    rule.signature,')
    add("\t}")
    add("}")
    add("")
    add("days_between(from_day, to_day) := n if {")
    add("\tn := (time.parse_ns(\"2006-01-02\", to_day) -")
    add("\t      time.parse_ns(\"2006-01-02\", from_day)) / 86400000000000")
    add("}")
    add("")

    export.policy = "\n".join(lines) + "\n"
    return export


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
